---
openapi: 3.0.3
info:
  title: API of transformation engine
  x-logo:
    url: .\docs\modules\ROOT\images\provoly.png
    backgroundColor: "#FFFFFF"
    altText: "Provoly logo"
  description: The transformation engine API can be used to configure transformations.
  version: 0.9.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080
    description: No sandbox environment as of now
paths:
  /about/version:
    get:
      summary: Returns the deployed application and helm package version
      operationId: getVersion
      tags:
        - Version
      security: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
              examples:
                response example:
                  summary: response
                  value:
                    applicationVersion: dev
                    chartVersion: dev
  /transfos:
    get:
      tags:
        - Transfo
      summary: List all registered transformations and their details.
      operationId: findAllTransformations
      security:
        - oidc: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransfoDetailsDto'
        "401":
          description: Unauthenticated user
    put:
      tags:
        - Transfo
      summary: Create or update a transformation
      description: |
        Create and validate transformation.
        
        If the transformation already exists, then update parameters.
        
        Active transformations can't be updated.
        
        Return a TransfoStatus Class whose describe parameters and show errors.
      operationId: validateAndSave
      security:
        - oidc: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransfoDto'
            examples:
              good request:
                summary: Create/update transformation
                description: Request body content all needed information ton create / update a transformation
                value:
                  id: 9c99f2d5-6e33-4e18-825b-3352c631e431
                  title: filtre station velos
                  links:
                    - start:
                        id: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                        slot: 0
                      end:
                        id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                        slot: 0
                    - start:
                        id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                        slot: 0
                      end:
                        id: 67717502-77ca-408c-8200-9ec14620888d
                        slot: 0
                  nodes:
                    - gui:
                        pos:
                          - 132
                          - 198
                        size:
                          - 140
                          - 26
                      id: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                      spec:
                        datasetId: 423b5c01-1816-41d4-b358-200000000005
                      title: InputDatasource
                      type: com.provoly.common.transfo.InputDatasource
                    - gui:
                        pos:
                          - 246
                          - 403
                        size:
                          - 140
                          - 46
                      id: 67717502-77ca-408c-8200-9ec14620888d
                      spec:
                        dataset: 423b5c01-1816-41d4-b358-200000000010
                      title: OutputDataset
                      type: com.provoly.common.transfo.OutputDataset
                    - gui:
                        pos:
                          - 426
                          - 253
                        size:
                          - 140
                          - 26
                      id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                      spec:
                        attributeName: freeSpace
                        operator: GREATER_THAN
                        value: '50'
                      title: Filter
                      type: com.provoly.common.transfo.Filter
              bad request:
                summary: Error in body fields.
                description: In node section, the output and input dataset is the same.
                value:
                  id: 9c99f2d5-6e33-4e18-825b-3352c631e434
                  title: filtre station velos
                  links:
                    - start:
                        id: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                        slot: 0
                      end:
                        id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                        slot: 0
                    - start:
                        id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                        slot: 0
                      end:
                        id: 67717502-77ca-408c-8200-9ec14620888d
                        slot: 0
                  nodes:
                    - gui:
                        pos:
                          - 132
                          - 198
                        size:
                          - 140
                          - 26
                      id: b15c7f78-3dfe-40fb-91c7-77e13f1ab111
                      spec:
                        datasetId: 423b5c01-1816-41d4-b358-200000000010
                      title: InputDatasource
                      type: com.provoly.common.transfo.InputDatasource
                    - gui:
                        pos:
                          - 246
                          - 403
                        size:
                          - 140
                          - 46
                      id: 67717502-77ca-408c-8200-9ec146208222
                      spec:
                        dataset: 423b5c01-1816-41d4-b358-200000000010
                      title: OutputDataset
                      type: com.provoly.common.transfo.OutputDataset
                    - gui:
                        pos:
                          - 426
                          - 253
                        size:
                          - 140
                          - 26
                      id: ab9f19ab-e7e4-43e5-87bc-532cde7f3333
                      spec:
                        attributeName: freeSpace
                        operator: GREATER_THAN
                        value: '50'
                      title: Filter
                      type: com.provoly.common.transfo.Filter

              request type/corpse error:
                summary: Bad request type error
                description: Request body with wrong type whose doesnt reference any existent Class.
                value:
                  id: 9c99f2d5-6e33-4e18-825b-3352c631e43a
                  title: filtre station velos
                  links:
                    - start:
                        id: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                        slot: 0
                      end:
                        id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                        slot: 0
                    - start:
                        id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                        slot: 0
                      end:
                        id: 67717502-77ca-408c-8200-9ec14620888d
                        slot: 0
                  nodes:
                    - gui:
                        pos:
                          - 132
                          - 198
                        size:
                          - 140
                          - 26
                      id: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                      spec:
                        datasetId: 423b5c01-1816-41d4-b358-200000000005
                      title: InputDatasource
                      type: com.provoly.common.transfo.InputDatasource
                    - gui:
                        pos:
                          - 246
                          - 403
                        size:
                          - 140
                          - 46
                      id: 67717502-77ca-408c-8200-9ec14620888d
                      spec:
                        datasetDefinition: 423b5c01-1816-41d4-b358-200000000010
                      title: OutputDataset
                      type: wrong.path.example--------------------------------
                    - gui:
                        pos:
                          - 426
                          - 253
                        size:
                          - 140
                          - 26
                      id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                      spec:
                        attributeName: freeSpace
                        operator: GREATER_THAN
                        value: '50'
                      title: Filter
                      type: com.provoly.common.transfo.Filter
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfoStatus'
              examples:
                response:
                  summary: Create/update transformation
                  value:
                    errors: [ ]
                    status:
                      - nodeId: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                        outModel:
                          attributes:
                            freeSpace:
                              name: freeSpace
                              type: integer
                            name:
                              name: name
                              type: keyword
                            totalSpace:
                              name: totalSpace
                              type: integer
                        errors: [ ]
                      - nodeId: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                        outModel:
                          attributes:
                            freeSpace:
                              name: freeSpace
                              type: integer
                            name:
                              name: name
                              type: keyword
                            totalSpace:
                              name: totalSpace
                              type: integer
                        errors: [ ]
                      - nodeId: 67717502-77ca-408c-8200-9ec14620888d
                        outModel: {}
                        errors: [ ]

                content error response:
                  summary: Error in body fields.
                  value:
                    errors:
                      - link:
                          start:
                            id: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                            slot: 0
                          end:
                            id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                            slot: 0
                      - link:
                          start:
                            id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                            slot: 0
                          end:
                            id: 67717502-77ca-408c-8200-9ec14620888d
                            slot: 0
                    status:
                      - nodeId: 67717502-77ca-408c-8200-9ec146208222
                        outModel: {}
                        errors:
                          - code: NO_INPUT
                      - nodeId: ab9f19ab-e7e4-43e5-87bc-532cde7f3333
                        outModel: {}
                        errors:
                          - code: NO_INPUT
                      - nodeId: b15c7f78-3dfe-40fb-91c7-77e13f1ab111
                        outModel:
                          attributes:
                            freeSpace:
                              name: freeSpace
                              type: integer
                            name:
                              name: name
                              type: keyword
                            totalSpace:
                              name: totalSpace
                              type: integer
                        errors: [ ]
        "400":
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfoDto'
        "401":
          description: Unauthenticated user
        "404":
          description: Not found.
          content:
            application/json:
              examples:
                response:
                  value:
                    application: provoly-transfo-engine
                    code: NOT_FOUND
                    message: "Dataset : 423b5c01-1816-41d4-b358-200000000010 inexistant"
        "409":
          description: Conflict. Active transformation can't be updated, at least one job instance is running for this transformation.

  /transfos/id/{id}:
    get:
      tags:
        - Transfo
      summary: Retrieved information of a transformation.
      description: |
        Retrieve all transformation information referenced by given ID.
      operationId: getById
      security:
        - oidc: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfoDetailsDto'
              examples:
                get transfo:
                  summary: Get one transformation response
                  description: This transformation is a filter.
                  value:
                    id: 9c99f2d5-6e33-4e18-825b-3352c631e431
                    nodes:
                      - id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                        type: com.provoly.common.transfo.Filter
                        title: Filter
                        gui:
                          pos:
                            - 426
                            - 253
                          size:
                            - 140
                            - 26
                        spec:
                          attributeName: freeSpace
                          operator: GREATER_THAN
                          value: '50'
                      - id: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                        type: com.provoly.common.transfo.InputDatasource
                        title: InputDatasource
                        gui:
                          pos:
                            - 132
                            - 198
                          size:
                            - 140
                            - 26
                        spec:
                          datasetId: 423b5c01-1816-41d4-b358-200000000005
                      - id: 67717502-77ca-408c-8200-9ec14620888d
                        type: com.provoly.common.transfo.OutputDataset
                        title: OutputDataset
                        gui:
                          pos:
                            - 246
                            - 403
                          size:
                            - 140
                            - 46
                        spec:
                          dataset: 423b5c01-1816-41d4-b358-200000000010
                    links:
                      - start:
                          id: b15c7f78-3dfe-40fb-91c7-77e13f1aba8c
                          slot: 0
                        end:
                          id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                          slot: 0
                      - start:
                          id: ab9f19ab-e7e4-43e5-87bc-532cde7f1aeb
                          slot: 0
                        end:
                          id: 67717502-77ca-408c-8200-9ec14620888d
                          slot: 0
                    title: filtre station velos
                    nodeNumber: 3
                    creationDate: '2023-07-28 14:08:21'
                    active: false
        "401":
          description: Unauthenticated user
        "404":
          description: The given ID does not reference any transformation.


    delete:
      tags:
        - Transfo
      summary: Delete a transformation
      description: |
        Delete the referenced transformation in given ID. 
        Nodes and links are deleted too.
      operationId: delete
      security:
        - oidc: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        "204":
          description: Transformation deleted.
        "401":
          description: Unauthenticated user
        "404":
          description: The given ID does not reference any transformation.
  /transfos/id/{id}/activation:
    post:
      tags:
        - Transfo
      summary: Create a Job Instance for the referenced transformation.
      description: Activate the referenced transformation. That generates a job instance that will execute the transformation. If the transformation is invalid, an error message is returned. Also note that invalid transformation can't be activated.

      operationId: activate
      security:
        - oidc: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        "201":
          description: Created.
        "400":
          description: Thrown when activating an invalid transformation.
        "404":
          description: The given ID does not reference any transformation.
        "409":
          description: Thrown when transformation have the same input and output dataset.
        "500":
          description: Thrown when transformation nodes and links form a cyclic graph which the engine doesn't support.
    delete:
      tags:
        - Transfo
      summary: Deactivation of a transformation.
      description: Deactivate the referenced ID in the given parameters. Deactivate a transformation means delete all linked job instances. If any error is thrown jobs are not deleted.
      operationId: deactivate
      security:
        - oidc: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        "204":
          description: Deleted.
        "404":
          description: The given ID does not reference any transformation.
        "409":
          description: |
            Thrown when deactivating an inactive transformation.

  /transfos/id/{id}/status:
    get:
      tags:
        - Transfo
      summary: Return transformation status.
      description: |
        Return all details about given transformation with ID parameter.
      operationId: getStatus
      security:
        - oidc: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransfoStatus'
        "404":
          description: The given ID does not reference any transformation.
components:
  schemas:
    DataSourceProvidingDto:
      type: object
      properties:
        method:
          $ref: '#/components/schemas/ProvidingMethod'
        dataSourceId:
          $ref: '#/components/schemas/UUID'
    DatasetOutcomeDto:
      type: object
      properties:
        method:
          $ref: '#/components/schemas/OutcomeMethod'
        datasetId:
          $ref: '#/components/schemas/UUID'
    ExecutionStatus:
      enum:
        - STARTED
        - TERMINATED
        - ERROR
      type: string
    GuiDto:
      type: object
      properties:
        pos:
          type: array
          items:
            format: int32
            type: integer
        size:
          type: array
          items:
            format: int32
            type: integer
    Instant:
      format: date-time
      type: string
      example: 2022-03-10T16:15:50Z
    IntermediateModel:
      type: object
      properties:
        attributes:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IntermediateModelAttribute'
    IntermediateModelAttribute:
      type: object
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/Type'
    JobExecutionDetailsDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        instance:
          $ref: '#/components/schemas/JobInstanceDetailsDto'
        status:
          $ref: '#/components/schemas/ExecutionStatus'
        executionDate:
          $ref: '#/components/schemas/Instant'
    JobInstanceDetailsDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        model:
          $ref: '#/components/schemas/JobModelDto'
        inDataSources:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/DataSourceProvidingDto'
        outDatasets:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/DatasetOutcomeDto'
        parametersValue:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ParameterValueDto'
        active:
          type: boolean
    JobModelDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        image:
          type: string
        parameters:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ParameterDto'
    LinkDto:
      type: object
      properties:
        start:
          $ref: '#/components/schemas/SlotDto'
        end:
          $ref: '#/components/schemas/SlotDto'
    NodeDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        type:
          type: string
        title:
          type: string
        gui:
          $ref: '#/components/schemas/GuiDto'
        spec:
          $ref: '#/components/schemas/NodeSpec'
    NodeSpec:
      type: object
    OutcomeMethod:
      enum:
        - KAFKA_TOPIC
      type: string
    ParameterDto:
      type: object
      properties:
        name:
          type: string
    ParameterValueDto:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    ProvidingMethod:
      enum:
        - KAFKA_TOPIC
      type: string
    SlotDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        slot:
          format: int32
          type: integer
    TransfoDetailsDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/NodeDto'
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkDto'
        title:
          type: string
        description:
          type: string
        nodeNumber:
          format: int32
          type: integer
        creationDate:
          $ref: '#/components/schemas/Instant'
        jobInstanceId:
          $ref: '#/components/schemas/UUID'
        active:
          type: boolean
        lastJobExecution:
          $ref: '#/components/schemas/JobExecutionDetailsDto'
    TransfoDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/NodeDto'
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkDto'
        title:
          type: string
        description:
          type: string
    TransfoError:
      type: object
    TransfoNodeError:
      type: object
    TransfoNodeStatus:
      type: object
      properties:
        nodeId:
          $ref: '#/components/schemas/UUID'
        outModel:
          $ref: '#/components/schemas/IntermediateModel'
        errors:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/TransfoNodeError'
    TransfoStatus:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/TransfoError'
        status:
          type: array
          items:
            $ref: '#/components/schemas/TransfoNodeStatus'
    Type:
      enum:
        - string
        - keyword
        - integer
        - long
        - decimal
        - raw
        - instant
        - Point
        - MultiPoint
        - LineString
        - MultiLineString
        - Polygon
        - MultiPolygon
      type: string
    UUID:
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
      type: string
    Version:
      type: object
      properties:
        applicationVersion:
          type: string
        chartVersion:
          type: string
  securitySchemes:
    oidc:
      type: openIdConnect
      description: Authentication
      openIdConnectUrl: /auth/realms/provoly/.well-known/openid-configuration